package com.webservicesproject.project.config;

import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.webservicesproject.project.entities.User;
import com.webservicesproject.project.repositories.UserRepository;

@Configuration
@Profile("test") //same name as the one in 'application.properties'
public class TestConfig implements CommandLineRunner {
	
	@Autowired //spring is now associating an instance of 'UserRepository' to my 'TestConfig'
	private UserRepository userRepository;

	@Override
	public void run(String... args) throws Exception {
		//the id is going to be generated by the database
		User u1 = new User(null, "Maria Brow", "maria@gmail.com", "988888888", "123456");
		User u2 = new User(null, "Alex Green", "alex@gmail.com", "977777777", "123456");
		
		userRepository.saveAll(Arrays.asList(u1, u2));
	}
}
